In [ ]:
#basic array creation ==========================================================>
import numpy as np
arr = np.array([1,2,3,4])
arr

In [6]:
a = [1,2,3,4.5,"hiii"]
a

[1, 2, 3, 4.5, 'hiii']

In [7]:
np.array(a)

array(['1', '2', '3', '4.5', 'hiii'], dtype='<U32')

In [8]:
b = [[1,2,3],[2,5,7],[6,8,9]]
b

[[1, 2, 3], [2, 5, 7], [6, 8, 9]]

In [9]:
np.array(b)

array([[1, 2, 3],
       [2, 5, 7],
       [6, 8, 9]])

In [ ]:
#array generate function =======================================>

In [12]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
arr = np.linspace(0,1,30)
arr

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [ ]:
#random generation function ===============================================>

In [25]:

# normalization concept (value b/w 0 - 1)
arr = np.random.rand(7)
arr

array([0.14547003, 0.88437683, 0.8483297 , 0.18211049, 0.63904065,
       0.50567279, 0.20097995])

In [26]:
# standardization concept (value b/w -3 to +3)
arr = np.random.randn(7)
arr

array([ 0.37581457,  0.72811856, -0.85046325,  0.64245278, -0.20868407,
        0.6928764 , -1.57593747])

In [31]:
#normal random number =============>
arr = np.random.randint(10)
arr

4

In [30]:
arr = np.random.randint(10,30,10)
arr

array([17, 12, 28, 20, 27, 29, 13, 23, 16, 27], dtype=int32)

In [ ]:
# array attributes =================================>

In [36]:
arr = np.array([[1,2,3],[4,5,6],[5,7,8],[8,9,5]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [5, 7, 8],
       [8, 9, 5]])

In [37]:
arr.shape

(4, 3)

In [38]:
arr.size

12

In [39]:
arr.dtype

dtype('int64')

In [ ]:
# array methods ===============================================>

In [51]:
arr = np.array([[1,2,3],[4,5,6],[7,8,5]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 5]])

In [52]:
arr.max()

np.int64(8)

In [53]:
arr.min()

np.int64(1)

In [54]:
# row wise sum >
np.sum(arr, axis = 1)

array([ 6, 15, 20])

In [55]:
# column wise sum >
np.sum(arr, axis = 0)

array([12, 15, 14])

In [56]:
arr.mean()

np.float64(4.555555555555555)

In [57]:
arr.std()

np.float64(2.1659542988464366)

In [58]:
arr.argmax()

np.int64(7)

In [59]:
arr.argmin()

np.int64(0)

In [ ]:
# reshaping and resizing the array ============================================>

In [68]:
arr = np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [69]:
arr = arr.reshape(5,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [70]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [ ]:
# NUMPY INDEXING AND SLICING OF VECTORS ===========================================================>

In [71]:
arr = np.arange(20,51)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [74]:
# indexing >
arr[4] , arr[5] , arr[0]

(np.int64(24), np.int64(25), np.int64(20))

In [80]:
# slicing >
arr[1:6] , arr[:4] , arr[:] , arr[27:] , arr[2::2]

(array([21, 22, 23, 24, 25]),
 array([20, 21, 22, 23]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([47, 48, 49, 50]),
 array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]))

In [ ]:
# NUMPY INDEXING AND SLICING OF MATRIX ===============================================================>

In [81]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [84]:
# rows came - print rows >
arr[0] , arr[1] , arr[2] , arr[3] , arr[4]  

(array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25]))

In [89]:
#columns came - print columns >
arr[:,0] , arr[:,1] , arr[:,2]

(array([ 1,  6, 11, 16, 21, 26]),
 array([ 2,  7, 12, 17, 22, 27]),
 array([ 3,  8, 13, 18, 23, 28]))

In [86]:
#slice single element by indexing >
arr[0,0] , arr[5,4]

(np.int64(1), np.int64(30))

In [87]:
# slicing more elements by indexing >
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [94]:
arr = np.arange(1,21).reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [98]:
slice = arr[2:4,2:4]
slice

array([[11, 12],
       [15, 16]])

In [99]:
slice = arr[3:5,2:4]
slice

array([[15, 16],
       [19, 20]])

In [101]:
slice = arr[3:,2:]
slice

array([[15, 16],
       [19, 20]])

In [ ]:
#BOOLEAN INDEXING =============================================================>

In [102]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [104]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])

In [ ]:
# ARRAY OPERATIONS ==========================================================================>

In [106]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

array([ 6,  7,  8,  9, 10])

In [107]:
# arithmatic operation >
a1 + a2

array([ 7,  9, 11, 13, 15])

In [108]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [109]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [110]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [111]:
a1 // a2

array([0, 0, 0, 0, 0])

In [112]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
# BROADCASTING ===================================================================>

In [113]:
# broadcasting in vectors >
l = [10,20,30,40]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50])

In [114]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [115]:
# brodcasting in matrix >
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
# DEEP AND SHALLOW COPY =====================================================================>

In [116]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [120]:
slice = arr[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [121]:
# original array remains the same (shallow copy) >
arr  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [122]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [123]:
b = arr
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [124]:
b[0] = 1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [128]:
# b change and a is also chnaged (deep copy) >
arr

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [131]:
# not to do deep copy >
b[0] = 11111
b

array([11111,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20])

In [136]:
arr

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [ ]:
# MATRIX OPERATIONS ==================================================================================>

In [137]:
A = np.array([[1,2],[4,5]])
B = np.array([[6,7],[8,9]])
A

array([[1, 2],
       [4, 5]])

In [138]:
B 

array([[6, 7],
       [8, 9]])

In [139]:
#matrix multiplication >
A @ B 

array([[22, 25],
       [64, 73]])

In [140]:
# another way >
np.dot(A,B)

array([[22, 25],
       [64, 73]])

In [142]:
# transpose >
A.T , B.T

(array([[1, 4],
        [2, 5]]),
 array([[6, 8],
        [7, 9]]))

In [ ]:
# ADVANCE ARRAY MANIPULATION ===========================================================================>

In [ ]:
#stack manipulation (vstack,hstack,simple) only use vectors , you cant use matrix 

In [150]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

np.vstack((arr1, arr2))

array([[1, 2, 3],
       [5, 6, 7]])

In [151]:
np.hstack((arr1, arr2))

array([1, 2, 3, 5, 6, 7])

In [152]:
np.column_stack((arr1, arr2))

array([[1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
# splitting array (hsplit, vsplit)

In [156]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [157]:
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [158]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [ ]:
# EXCERSIZES  

In [173]:
# valid suduko

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

# valid for rows
b = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("it is a not valid sudoko")
        break
else:
        print("valid for rows")
   

valid for rows


In [174]:
# valid for column
c = np.sum(s,axis = 1)
for i in b:
    if i != 45:
        print("it is a not valid sudoko")
        break
else:
        print("valid for columns")

valid for columns


In [175]:
# valid for blocks
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
# GENERAL QUESTIIONS ========================================================>

In [177]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [178]:
#Get the shape of the matrix
data.shape


(5, 3)

In [179]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [180]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [181]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [184]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [185]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [186]:
#Increase Math marks of all students by 5.
data[:,1] +=5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [188]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [193]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [195]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])